# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 718dcb1623530b24b2bfb7dc8044708cfa0e5c05e6719cf389f10eaa3efcb143719be35b6366eed6fd727ff45ecfe1d8783bf618859c5c76f92eb45c0ada118b

test:
  secret_key_base: a6dbb1fa3eb5eb38183c6d44a964d0f1bc4a8662d79720ed0bd1dd1de19fe5c0ecb5e207f248a52b4a9f96531adb28e312ad498683b2da54e2c8016bb5f260a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
